apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gwt7x53xn-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gwt7x53xn-dotnet-basic-gitops