apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gwt7x53xn-dotnet-basic
  janus-idp.io/tekton: gwt7x53xn-dotnet-basic
  backstage.io/kubernetes-id: gwt7x53xn-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gwt7x53xn-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
